project:
  type: book
  output-dir: docs

book:
  title: "R notes"
  author: "Lin Zheng"
  date: "2024/8/10"
  
  reader-mode: true
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://linzhengmix.github.io/r_notes/
  repo-branch: main
  
  chapters:
    - index.qmd
    - 使用R语言画ISME中的进化树.qmd
    - 总结.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

